[package]
authors = ["Hirokazu Nakanishi <nakanisi.hirokazu@jp.panasonic.com>"]
name = "fft-analyzer"
edition = "2024"
version = "0.1.0"

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false

[dependencies]
embassy-stm32 = { version = "0.6", features = ["defmt", "stm32h753zi", "time-driver-tim2", "exti", "memory-x", "chrono"] }
embassy-sync = { version = "0.8", features = ["defmt"] }
embassy-embedded-hal = { version = "0.6" }
embassy-executor = { version = "0.10", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb = { version = "0.6", features = ["defmt"] }
embassy-futures = { version = "0.1" }

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
semihosting = "0.1.20"
libm = "0.2"
micromath = "2.1.0"
static_cell = "2"
grounded = "0.2"
flip-link = "0.1.12"

[dev-dependencies]
defmt-test = "0.3"

# cargo build/run
[profile.dev]
opt-level = 0
codegen-units = 1

# cargo build/run --release
[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true
strip = true
panic = 'abort'
